"""Adversarial tests for formal XHS parent/child supervision wiring."""

from __future__ import annotations

import sys
from importlib import import_module
from pathlib import Path
from typing import Any

import pytest

from trippostcollect.xhs.leases import LeaseSubprocessResult
from trippostcollect.xhs.runtime import (
    RUNTIME_STATUS_AUTH_KEY_ENV,
    RuntimeStatusValidationError,
)
from trippostcollect.xhs.supervision import (
    PARENT_WATCHDOG_POLL_SECONDS,
    PARENT_WATCHDOG_RESUME_GRACE_SECONDS,
    PARENT_WATCHDOG_STALE_AFTER_SECONDS,
    PARENT_WATCHDOG_STARTUP_GRACE_SECONDS,
    parent_runtime_watchdog_policy,
    run_supervised_xhs_subprocess,
    runtime_watchdog_evidence,
)


ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))
xhs_runner = import_module("xhs_runner")
repair_xhs_posts = import_module("repair_xhs_posts")


class RecordingGuard:
    run_id = "run-1"

    def __init__(self, result: LeaseSubprocessResult | BaseException) -> None:
        self.result = result
        self.calls: list[dict[str, Any]] = []

    def run_subprocess(self, command, **kwargs):
        self.calls.append({"command": list(command), **kwargs})
        if isinstance(self.result, BaseException):
            raise self.result
        return self.result


def subprocess_result(
    *,
    termination_reason: str | None = None,
    timed_out: bool = False,
    runtime_status: dict[str, Any] | None = None,
) -> LeaseSubprocessResult:
    return LeaseSubprocessResult(
        args=["child"],
        returncode=124 if timed_out else 0,
        stdout="",
        stderr="",
        timed_out=timed_out,
        termination_reason=termination_reason,
        runtime_status=runtime_status,
        watchdog_resume_grace_used=False,
    )


def public_status(**overrides: Any) -> dict[str, Any]:
    value = {
        "writer_role": "mediacrawler_supervisor",
        "sequence": 7,
        "heartbeat_at": "2026-09-03T08:00:00+00:00",
        "phase": "running",
        "network_state": "network_paused",
        "network_reason": "ReadTimeout",
        "auth_tag": "secret-tag-must-not-leak",
        "lease_id": "secret-lease-id-must-not-leak",
    }
    value.update(overrides)
    return value


def test_formal_watchdog_has_no_whole_run_deadline_and_bounded_liveness() -> None:
    policy = parent_runtime_watchdog_policy()

    assert policy.startup_grace_seconds == PARENT_WATCHDOG_STARTUP_GRACE_SECONDS == 120.0
    assert policy.stale_after_seconds == PARENT_WATCHDOG_STALE_AFTER_SECONDS == 60.0
    assert policy.poll_seconds == PARENT_WATCHDOG_POLL_SECONDS == 5.0
    assert policy.resume_grace_seconds == PARENT_WATCHDOG_RESUME_GRACE_SECONDS == 30.0
    assert policy.poll_seconds < policy.stale_after_seconds
    assert not hasattr(policy, "runtime_seconds")
    assert not hasattr(policy, "absolute_timeout_seconds")


def test_formal_and_repair_use_the_same_supervision_boundary() -> None:
    assert xhs_runner.run_supervised_xhs_subprocess is run_supervised_xhs_subprocess
    assert repair_xhs_posts.run_supervised_xhs_subprocess is run_supervised_xhs_subprocess


def test_supervised_child_passes_one_fixed_watchdog_without_mutating_environment(
    tmp_path: Path,
) -> None:
    result = subprocess_result(runtime_status=public_status())
    guard = RecordingGuard(result)
    env = {"TRIPPOSTCOLLECT_XHS_RUN_ID": "run-1", "VISIBLE": "value"}

    observed = run_supervised_xhs_subprocess(
        guard,  # type: ignore[arg-type]
        ["python", "child.py"],
        cwd=tmp_path,
        env=env,
    )

    assert observed is result
    assert env == {"TRIPPOSTCOLLECT_XHS_RUN_ID": "run-1", "VISIBLE": "value"}
    assert len(guard.calls) == 1
    call = guard.calls[0]
    assert call["command"] == ["python", "child.py"]
    assert call["cwd"] == tmp_path
    assert call["env"] is env
    assert "timeout_seconds" not in call
    assert call["runtime_watchdog"] == parent_runtime_watchdog_policy()


@pytest.mark.parametrize(
    "env, error",
    [
        ({}, "wrong run id"),
        ({"TRIPPOSTCOLLECT_XHS_RUN_ID": "run-2"}, "wrong run id"),
        (
            {
                "TRIPPOSTCOLLECT_XHS_RUN_ID": "run-1",
                RUNTIME_STATUS_AUTH_KEY_ENV: "0" * 64,
            },
            "must be generated by LeaseGuard",
        ),
    ],
)
def test_supervised_child_rejects_identity_or_secret_injection_before_spawn(
    tmp_path: Path,
    env: dict[str, str],
    error: str,
) -> None:
    guard = RecordingGuard(subprocess_result())

    with pytest.raises(ValueError, match=error):
        run_supervised_xhs_subprocess(
            guard,  # type: ignore[arg-type]
            ["child"],
            cwd=tmp_path,
            env=env,
        )

    assert guard.calls == []


def test_supervised_child_propagates_failure_without_a_second_spawn(
    tmp_path: Path,
) -> None:
    guard = RecordingGuard(OSError("spawn failed"))

    with pytest.raises(OSError, match="spawn failed"):
        run_supervised_xhs_subprocess(
            guard,  # type: ignore[arg-type]
            ["child"],
            cwd=tmp_path,
            env={"TRIPPOSTCOLLECT_XHS_RUN_ID": "run-1"},
        )

    assert len(guard.calls) == 1


def test_watchdog_evidence_keeps_network_pause_but_strips_private_fields() -> None:
    evidence = runtime_watchdog_evidence(
        subprocess_result(runtime_status=public_status())
    )

    assert evidence["enabled"] is True
    assert evidence["absolute_runtime_timeout_enabled"] is False
    assert evidence["termination_reason"] is None
    assert evidence["timed_out"] is False
    assert evidence["last_status"] == {
        "writer_role": "mediacrawler_supervisor",
        "sequence": 7,
        "heartbeat_at": "2026-09-03T08:00:00+00:00",
        "phase": "running",
        "network_state": "network_paused",
        "network_reason": "ReadTimeout",
    }
    serialized = repr(evidence)
    assert "secret-tag-must-not-leak" not in serialized
    assert "secret-lease-id-must-not-leak" not in serialized


def test_watchdog_evidence_fails_closed_on_incomplete_status() -> None:
    status = public_status()
    status.pop("network_reason")

    with pytest.raises(RuntimeStatusValidationError, match="missing fields"):
        runtime_watchdog_evidence(subprocess_result(runtime_status=status))


def test_watchdog_timeout_reason_is_explicit_and_not_relabelled_as_network() -> None:
    evidence = runtime_watchdog_evidence(
        subprocess_result(
            termination_reason="runtime_status_stale",
            timed_out=True,
            runtime_status=public_status(network_state="online", network_reason=""),
        )
    )

    assert evidence["termination_reason"] == "runtime_status_stale"
    assert evidence["timed_out"] is True
    assert evidence["last_status"]["network_state"] == "online"
