"""Fail-closed parent supervision for one run-scoped XHS child."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Callable, Mapping, Sequence

from trippostcollect.xhs.leases import (
    LeaseGuard,
    LeaseSubprocessResult,
    RuntimeStatusWatchdogPolicy,
)
from trippostcollect.xhs.runtime import (
    RUNTIME_STATUS_AUTH_KEY_ENV,
    public_runtime_status,
)


PARENT_WATCHDOG_STARTUP_GRACE_SECONDS = 120.0
PARENT_WATCHDOG_STALE_AFTER_SECONDS = 60.0
PARENT_WATCHDOG_POLL_SECONDS = 5.0
PARENT_WATCHDOG_RESUME_GRACE_SECONDS = 30.0
XHS_RUNTIME_RUN_ID_ENV = "TRIPPOSTCOLLECT_XHS_RUN_ID"


def parent_runtime_watchdog_policy() -> RuntimeStatusWatchdogPolicy:
    """Return the fixed liveness policy; it deliberately has no run deadline."""

    return RuntimeStatusWatchdogPolicy(
        startup_grace_seconds=PARENT_WATCHDOG_STARTUP_GRACE_SECONDS,
        stale_after_seconds=PARENT_WATCHDOG_STALE_AFTER_SECONDS,
        poll_seconds=PARENT_WATCHDOG_POLL_SECONDS,
        resume_grace_seconds=PARENT_WATCHDOG_RESUME_GRACE_SECONDS,
    )


def run_supervised_xhs_subprocess(
    guard: LeaseGuard,
    command: Sequence[str],
    *,
    cwd: Path,
    env: Mapping[str, str],
    timeout_seconds: int,
    progress_callback: Callable[[], None] | None = None,
) -> LeaseSubprocessResult:
    """Run one exact child with authenticated monotonic liveness supervision."""

    if str(env.get(XHS_RUNTIME_RUN_ID_ENV) or "") != guard.run_id:
        raise ValueError("XHS supervised child environment has the wrong run id")
    if RUNTIME_STATUS_AUTH_KEY_ENV in env:
        raise ValueError("XHS runtime status auth key must be generated by LeaseGuard")
    return guard.run_subprocess(
        command,
        cwd=cwd,
        env=env,
        timeout_seconds=timeout_seconds,
        runtime_watchdog=parent_runtime_watchdog_policy(),
        **({"progress_callback": progress_callback} if progress_callback is not None else {}),
    )


def runtime_watchdog_evidence(
    result: LeaseSubprocessResult | None,
) -> dict[str, Any]:
    """Return a secret-free audit projection suitable for state and summaries."""

    policy = parent_runtime_watchdog_policy()
    last_status = None
    if result is not None and result.runtime_status is not None:
        last_status = public_runtime_status(result.runtime_status)
    return {
        "enabled": True,
        "absolute_runtime_timeout_enabled": False,
        "startup_grace_seconds": policy.startup_grace_seconds,
        "stale_after_seconds": policy.stale_after_seconds,
        "poll_seconds": policy.poll_seconds,
        "resume_grace_seconds": policy.resume_grace_seconds,
        "termination_reason": result.termination_reason if result is not None else None,
        "timed_out": bool(result.timed_out) if result is not None else False,
        "resume_grace_used": (
            bool(result.watchdog_resume_grace_used) if result is not None else False
        ),
        "last_status": last_status,
    }
