"""平台适配 T00 的静态处置规则；按顺序首个完整匹配生效。"""

# 测试目标相对仓库根；显式标记 F 节指定关系及按模块职责判断的补充归属。
TEST_FILE_RULES = {
    "tests/test_adapter_ledger.py": {
        "target_file": "tests/test_adapter_ledger.py",
        "protects": "F10",
        "card": "T00",
        "note": "验证迁移规则、产物重现与旧节点台账，属于 T00 准备工具。",
        "spec_explicit": False,
    },
    "tests/test_adaptive_accumulator.py": {
        "target_file": "tests/application/test_discovery.py",
        "protects": "F01",
        "card": "T03",
        "note": "测试共享候选累加器，与 F01 fork 累加器共同归 T03。",
        "spec_explicit": False,
    },
    "tests/test_author_avatar_migration.py": {
        "target_file": "tests/test_author_avatar_migration.py",
        "protects": "F04",
        "card": "T04",
        "note": "测试 db.avatar_migration 的历史净化，现有数据库模块原位保留。",
        "spec_explicit": False,
    },
    "tests/test_author_avatar_sanitization.py": {
        "target_file": "tests/records/test_serialization.py",
        "protects": "F04",
        "card": "T04",
        "note": "F04 首次序列化净化。",
        "spec_explicit": True,
    },
    "tests/test_bilibili_article_detail.py": {
        "target_file": "tests/platforms/bilibili/test_bilibili_article_detail.py",
        "protects": "F14",
        "card": "T08",
        "note": "F14 指定平台目标；根路由集成保护语义仍须保留。",
        "spec_explicit": True,
    },
    "tests/test_bilibili_article_repair.py": {
        "target_file": "tests/test_bilibili_article_repair.py",
        "protects": "F08",
        "card": "T10",
        "note": "F08 B站修复保持根文件，T10 承担辅助入口。",
        "spec_explicit": True,
    },
    "tests/test_bilibili_formal_route.py": {
        "target_file": "tests/platforms/bilibili/test_bilibili_formal_route.py",
        "protects": "F14",
        "card": "T08",
        "note": "F14 指定平台目标；根路由集成保护语义仍须保留。",
        "spec_explicit": True,
    },
    "tests/test_bilibili_image_materialization.py": {
        "target_file": "tests/platforms/bilibili/test_bilibili_image_materialization.py",
        "protects": "F14",
        "card": "T08",
        "note": "F14 指定平台目标；根路由集成保护语义仍须保留。",
        "spec_explicit": True,
    },
    "tests/test_crawl_policy.py": {
        "target_file": "tests/application/test_policy.py",
        "protects": "F07",
        "card": "T04",
        "note": "测试共享节流策略；C8 crawl_policy 整体迁 application/policy，归 T04。",
        "spec_explicit": False,
    },
    "tests/test_crawl_runner_parallel.py": {
        "target_file": "tests/test_crawl_runner_parallel.py",
        "protects": "F06",
        "card": "T02",
        "note": "测试通用调度并行和进程终止；调度器原位保留，进程运行边界归 T02。",
        "spec_explicit": False,
    },
    "tests/test_discovery_checkpoints.py": {
        "target_file": "tests/application/test_discovery.py",
        "protects": "F01",
        "card": "T03",
        "note": "F01 明确指定发现与候选决策迁移目标。",
        "spec_explicit": True,
    },
    "tests/test_failure_classifier.py": {
        "target_file": "tests/application/test_failures.py",
        "protects": "F06",
        "card": "T04",
        "note": "测试共享失败分类；C8 failure_classifier 归 application/failures 与 T04。",
        "spec_explicit": False,
    },
    "tests/test_frozen_files.py": {
        "target_file": "tests/test_frozen_files.py",
        "protects": "F10",
        "card": "T12",
        "note": "测试冻结契约完整性，随 T12 构建与安装资源治理核验。",
        "spec_explicit": False,
    },
    "tests/test_full_content_contract.py": {
        "target_file": "tests/records/test_formal.py",
        "protects": "F03",
        "card": "T04",
        "note": "F03 正式字段与内容契约。",
        "spec_explicit": True,
    },
    "tests/test_image_candidates.py": {
        "target_file": "tests/test_image_candidates.py",
        "protects": "F05",
        "card": "T11",
        "note": "测试现有 artifacts 图片候选、清单、字节及持久化模块，保持根核心归属；由 T11 正式媒体事务集成。",
        "spec_explicit": False,
    },
    "tests/test_image_manifest.py": {
        "target_file": "tests/test_image_manifest.py",
        "protects": "F05",
        "card": "T11",
        "note": "测试现有 artifacts 图片候选、清单、字节及持久化模块，保持根核心归属；由 T11 正式媒体事务集成。",
        "spec_explicit": False,
    },
    "tests/test_image_materialization.py": {
        "target_file": "tests/test_image_materialization.py",
        "protects": "F05",
        "card": "T11",
        "note": "测试现有 artifacts 图片候选、清单、字节及持久化模块，保持根核心归属；由 T11 正式媒体事务集成。",
        "spec_explicit": False,
    },
    "tests/test_image_persistence.py": {
        "target_file": "tests/test_image_persistence.py",
        "protects": "F05",
        "card": "T11",
        "note": "测试现有 artifacts 图片候选、清单、字节及持久化模块，保持根核心归属；由 T11 正式媒体事务集成。",
        "spec_explicit": False,
    },
    "tests/test_image_runner_contract.py": {
        "target_file": "tests/test_image_runner_contract.py",
        "protects": "F05",
        "card": "T11",
        "note": "测试 runner 正文图片门禁与提交契约，由 T11 内容提交链负责。",
        "spec_explicit": False,
    },
    "tests/test_login_warmup.py": {
        "target_file": "tests/application/test_warmup.py",
        "protects": "F07",
        "card": "T10",
        "note": "F07 辅助登录入口。",
        "spec_explicit": True,
    },
    "tests/test_mediacrawler_behavior.py": {
        "target_file": "tests/runtime/test_behavior.py",
        "protects": "F07",
        "card": "T04",
        "note": "F07 共享行为机制。",
        "spec_explicit": True,
    },
    "tests/test_mediacrawler_import.py": {
        "target_file": "tests/application/test_content_commit.py",
        "protects": "F05",
        "card": "T11",
        "note": "F05 内容事务和媒体提交；按 T11 迁移根提交链。",
        "spec_explicit": True,
    },
    "tests/test_mediacrawler_pagination.py": {
        "target_file": "tests/application/test_discovery.py",
        "protects": "F01",
        "card": "T03",
        "note": "F01 明确指定发现与候选决策迁移目标。",
        "spec_explicit": True,
    },
    "tests/test_mediacrawler_process_watchdog.py": {
        "target_file": "tests/test_mediacrawler_process_watchdog.py",
        "protects": "F06",
        "card": "T02",
        "note": "F06 原根职责文件改导入；进程管理归 T02。",
        "spec_explicit": True,
    },
    "tests/test_post_detail_repair.py": {
        "target_file": "tests/application/test_repair.py",
        "protects": "F08",
        "card": "T10",
        "note": "F08 通用精确详情修复。",
        "spec_explicit": True,
    },
    "tests/test_remove_city_name.py": {
        "target_file": "tests/test_remove_city_name.py",
        "protects": "F03",
        "card": "T04",
        "note": "测试根数据库和记录字段边界，归 T04 正式记录契约；不迁入平台。",
        "spec_explicit": False,
    },
    "tests/test_residual_detail_fallbacks.py": {
        "target_file": "tests/platforms/test_repair_fallbacks.py",
        "protects": "F08",
        "card": "T10",
        "note": "F08 跨平台修复专属回退。",
        "spec_explicit": True,
    },
    "tests/test_run_ids.py": {
        "target_file": "tests/test_run_ids.py",
        "protects": "F10",
        "card": "T12",
        "note": "F10 只迁移 installation 职责；其余运行标识断言保持原位。",
        "spec_explicit": True,
        "target_by_lane": {"installation": "tests/test_platform_package_resources.py"},
    },
    "tests/test_run_lanes.py": {
        "target_file": "tests/test_run_lanes.py",
        "protects": "F10",
        "card": "T12",
        "note": "测试 CI 分组、隔离与执行守卫，归 T12 测试基础设施交接。",
        "spec_explicit": False,
    },
    "tests/test_topic_relevance.py": {
        "target_file": "tests/test_topic_relevance.py",
        "protects": "F03",
        "card": "T04",
        "note": "测试 records.topic_relevance 及数据库迁移，现有公共核心原位保留；归 T04 记录职责。",
        "spec_explicit": False,
    },
    "tests/test_xhs_batch_checkpoint.py": {
        "target_file": "tests/test_xhs_batch_checkpoint.py",
        "protects": "F02",
        "card": "T09",
        "note": "F02 根端发现提交与 ACK 保持根职责。",
        "spec_explicit": True,
    },
    "tests/test_xhs_discovery.py": {
        "target_file": "tests/test_xhs_discovery.py",
        "protects": "F01",
        "card": "T09",
        "note": "测试按账号隔离的根 XHS 发现记忆，由 T09 协同且不迁入平台。",
        "spec_explicit": False,
    },
    "tests/test_xhs_lease_exit.py": {
        "target_file": "tests/test_xhs_lease_exit.py",
        "protects": "F06",
        "card": "T09",
        "note": "测试根 XHS 租约退出与父进程监督，沿 F06 根所有权保持原位。",
        "spec_explicit": False,
    },
    "tests/test_xhs_leases.py": {
        "target_file": "tests/test_xhs_leases.py",
        "protects": "F06",
        "card": "T09",
        "note": "F06 根租约、监督与终态职责原位保留。",
        "spec_explicit": True,
    },
    "tests/test_xhs_parent_watchdog.py": {
        "target_file": "tests/test_xhs_parent_watchdog.py",
        "protects": "F06",
        "card": "T09",
        "note": "测试根 XHS 租约退出与父进程监督，沿 F06 根所有权保持原位。",
        "spec_explicit": False,
    },
    "tests/test_xhs_pool.py": {
        "target_file": "tests/test_xhs_pool.py",
        "protects": "F06",
        "card": "T09",
        "note": "测试根 XHS 账号池、配置和租约轮次，属于 T09 根控制边界。",
        "spec_explicit": False,
    },
    "tests/test_xhs_post_repair.py": {
        "target_file": "tests/test_xhs_post_repair.py",
        "protects": "F08",
        "card": "T09",
        "note": "F08 XHS 修复保持根文件，T09 承担根轮次与修复协同。",
        "spec_explicit": True,
    },
    "tests/test_xhs_runtime_status.py": {
        "target_file": "tests/test_xhs_runtime_status.py",
        "protects": "F06",
        "card": "T09",
        "note": "F06 根租约、监督与终态职责原位保留。",
        "spec_explicit": True,
    },
    "tests/test_xhs_supervision.py": {
        "target_file": "tests/test_xhs_supervision.py",
        "protects": "F06",
        "card": "T09",
        "note": "F06 根租约、监督与终态职责原位保留。",
        "spec_explicit": True,
    },
    "tests/test_xhs_terminalizer.py": {
        "target_file": "tests/test_xhs_terminalizer.py",
        "protects": "F06",
        "card": "T09",
        "note": "F06 根租约、监督与终态职责原位保留。",
        "spec_explicit": True,
    },
    "tools/MediaCrawler/tests/test_cdp_browser_lifecycle.py": {
        "target_file": "tests/runtime/test_cdp_browser_lifecycle.py",
        "protects": "F06",
        "card": "T02",
        "note": "F06 浏览器生命周期迁移。",
        "spec_explicit": True,
    },
    "tools/MediaCrawler/tests/test_cdp_browser.py": {
        "target_file": "tests/runtime/test_cdp_browser.py",
        "protects": "F06",
        "card": "T02",
        "note": "F06 浏览器生命周期迁移。",
        "spec_explicit": True,
    },
    "tools/MediaCrawler/tests/test_douyin_image_only.py": {
        "target_file": "tests/platforms/douyin/test_douyin_image_only.py",
        "protects": "F12",
        "card": "T06",
        "note": "F12 抖音平台保护语义。",
        "spec_explicit": True,
    },
    "tools/MediaCrawler/tests/test_douyin_no_user_info.py": {
        "target_file": "tests/platforms/douyin/test_douyin_no_user_info.py",
        "protects": "F12",
        "card": "T06",
        "note": "F12 抖音平台保护语义。",
        "spec_explicit": True,
    },
    "tools/MediaCrawler/tests/test_douyin_search_safety.py": {
        "target_file": "tests/platforms/douyin/test_douyin_search_safety.py",
        "protects": "F12",
        "card": "T06",
        "note": "F12 抖音平台保护语义。",
        "spec_explicit": True,
    },
    "tools/MediaCrawler/tests/test_douyin_store.py": {
        "target_file": "tests/platforms/douyin/test_douyin_store.py",
        "protects": "F12",
        "card": "T06",
        "note": "F12 抖音平台保护语义。",
        "spec_explicit": True,
    },
    "tools/MediaCrawler/tests/test_image_client_http_classification.py": {
        "target_file": "tests/artifacts/test_staging.py",
        "protects": "F05",
        "card": "T04",
        "note": "F05 图片重试、错误分类与 staging。",
        "spec_explicit": True,
    },
    "tools/MediaCrawler/tests/test_image_download_retry.py": {
        "target_file": "tests/artifacts/test_staging.py",
        "protects": "F05",
        "card": "T04",
        "note": "F05 图片重试、错误分类与 staging。",
        "spec_explicit": True,
    },
    "tools/MediaCrawler/tests/test_image_staging_errors.py": {
        "target_file": "tests/artifacts/test_staging.py",
        "protects": "F05",
        "card": "T04",
        "note": "F05 图片重试、错误分类与 staging。",
        "spec_explicit": True,
    },
    "tools/MediaCrawler/tests/test_trippostcollect_adaptive.py": {
        "target_file": "tests/application/test_discovery.py",
        "protects": "F01",
        "card": "T03",
        "note": "F01 共享候选决策。",
        "spec_explicit": True,
    },
    "tools/MediaCrawler/tests/test_weibo_empty_search.py": {
        "target_file": "tests/platforms/weibo/test_weibo_empty_search.py",
        "protects": "F11",
        "card": "T05",
        "note": "F11 微博平台保护语义。",
        "spec_explicit": True,
    },
    "tools/MediaCrawler/tests/test_weibo_image_download.py": {
        "target_file": "tests/platforms/weibo/test_weibo_image_download.py",
        "protects": "F11",
        "card": "T05",
        "note": "F11 微博平台保护语义。",
        "spec_explicit": True,
    },
    "tools/MediaCrawler/tests/test_weibo_no_user_info.py": {
        "target_file": "tests/platforms/weibo/test_weibo_no_user_info.py",
        "protects": "F11",
        "card": "T05",
        "note": "F11 微博平台保护语义。",
        "spec_explicit": True,
    },
    "tools/MediaCrawler/tests/test_weibo_store.py": {
        "target_file": "tests/platforms/weibo/test_weibo_store.py",
        "protects": "F11",
        "card": "T05",
        "note": "F11 微博平台保护语义。",
        "spec_explicit": True,
    },
    "tools/MediaCrawler/tests/test_xhs_core_access_error.py": {
        "target_file": "tests/platforms/xhs/test_xhs_core_access_error.py",
        "protects": "F15",
        "card": "T09",
        "note": "F15 XHS 平台保护语义；不替代根租约、终态与 ACK。",
        "spec_explicit": True,
    },
    "tools/MediaCrawler/tests/test_xhs_creator_enrichment.py": {
        "target_file": "tests/platforms/xhs/test_xhs_creator_enrichment.py",
        "protects": "F15",
        "card": "T09",
        "note": "F15 XHS 平台保护语义；不替代根租约、终态与 ACK。",
        "spec_explicit": True,
    },
    "tools/MediaCrawler/tests/test_xhs_discovery_memory.py": {
        "target_file": "tests/platforms/xhs/test_xhs_discovery_memory.py",
        "protects": "F15",
        "card": "T09",
        "note": "F15 XHS 平台保护语义；不替代根租约、终态与 ACK。",
        "spec_explicit": True,
    },
    "tools/MediaCrawler/tests/test_xhs_image_download.py": {
        "target_file": "tests/platforms/xhs/test_xhs_image_download.py",
        "protects": "F15",
        "card": "T09",
        "note": "F15 XHS 平台保护语义；不替代根租约、终态与 ACK。",
        "spec_explicit": True,
    },
    "tools/MediaCrawler/tests/test_xhs_login_contract.py": {
        "target_file": "tests/platforms/xhs/test_xhs_login_contract.py",
        "protects": "F15",
        "card": "T09",
        "note": "F15 XHS 平台保护语义；不替代根租约、终态与 ACK。",
        "spec_explicit": True,
    },
    "tools/MediaCrawler/tests/test_xhs_manual_wait_budget.py": {
        "target_file": "tests/platforms/xhs/test_xhs_manual_wait_budget.py",
        "protects": "F15",
        "card": "T09",
        "note": "F15 XHS 平台保护语义；不替代根租约、终态与 ACK。",
        "spec_explicit": True,
    },
    "tools/MediaCrawler/tests/test_xhs_media_policy.py": {
        "target_file": "tests/platforms/xhs/test_xhs_media_policy.py",
        "protects": "F15",
        "card": "T09",
        "note": "F15 XHS 平台保护语义；不替代根租约、终态与 ACK。",
        "spec_explicit": True,
    },
    "tools/MediaCrawler/tests/test_xhs_midrun_login_recovery.py": {
        "target_file": "tests/platforms/xhs/test_xhs_midrun_login_recovery.py",
        "protects": "F15",
        "card": "T09",
        "note": "F15 XHS 平台保护语义；不替代根租约、终态与 ACK。",
        "spec_explicit": True,
    },
    "tools/MediaCrawler/tests/test_xhs_network_recovery.py": {
        "target_file": "tests/platforms/xhs/test_xhs_network_recovery.py",
        "protects": "F15",
        "card": "T09",
        "note": "F15 XHS 平台保护语义；不替代根租约、终态与 ACK。",
        "spec_explicit": True,
    },
    "tools/MediaCrawler/tests/test_xhs_popup_guard.py": {
        "target_file": "tests/platforms/xhs/test_xhs_popup_guard.py",
        "protects": "F15",
        "card": "T09",
        "note": "F15 XHS 平台保护语义；不替代根租约、终态与 ACK。",
        "spec_explicit": True,
    },
    "tools/MediaCrawler/tests/test_xhs_qrcode_login.py": {
        "target_file": "tests/platforms/xhs/test_xhs_qrcode_login.py",
        "protects": "F15",
        "card": "T09",
        "note": "F15 XHS 平台保护语义；不替代根租约、终态与 ACK。",
        "spec_explicit": True,
    },
    "tools/MediaCrawler/tests/test_xhs_qrcode_preview.py": {
        "target_file": "tests/platforms/xhs/test_xhs_qrcode_preview.py",
        "protects": "F15",
        "card": "T09",
        "note": "F15 XHS 平台保护语义；不替代根租约、终态与 ACK。",
        "spec_explicit": True,
    },
    "tools/MediaCrawler/tests/test_xhs_raw_response_errors.py": {
        "target_file": "tests/platforms/xhs/test_xhs_raw_response_errors.py",
        "protects": "F15",
        "card": "T09",
        "note": "F15 XHS 平台保护语义；不替代根租约、终态与 ACK。",
        "spec_explicit": True,
    },
    "tools/MediaCrawler/tests/test_xhs_shutdown_error_priority.py": {
        "target_file": "tests/platforms/xhs/test_xhs_shutdown_error_priority.py",
        "protects": "F15",
        "card": "T09",
        "note": "F15 XHS 平台保护语义；不替代根租约、终态与 ACK。",
        "spec_explicit": True,
    },
    "tools/MediaCrawler/tests/test_xhs_store_provenance.py": {
        "target_file": "tests/platforms/xhs/test_xhs_store_provenance.py",
        "protects": "F15",
        "card": "T09",
        "note": "F15 XHS 平台保护语义；不替代根租约、终态与 ACK。",
        "spec_explicit": True,
    },
    "tools/MediaCrawler/tests/test_zhihu_detail_images.py": {
        "target_file": "tests/platforms/zhihu/test_zhihu_detail_images.py",
        "protects": "F13",
        "card": "T07",
        "note": "F13 知乎平台保护语义。",
        "spec_explicit": True,
    },
    "tools/MediaCrawler/tests/test_zhihu_image_download.py": {
        "target_file": "tests/platforms/zhihu/test_zhihu_image_download.py",
        "protects": "F13",
        "card": "T07",
        "note": "F13 知乎平台保护语义。",
        "spec_explicit": True,
    },
    "tools/MediaCrawler/tests/test_zhihu_search_detail.py": {
        "target_file": "tests/platforms/zhihu/test_zhihu_search_detail.py",
        "protects": "F13",
        "card": "T07",
        "note": "F13 知乎平台保护语义。",
        "spec_explicit": True,
    },
}

# 字段依次为文件、限定名正则、目标、处置、任务卡、测试责任和备注。
# 从原型的 r 与 store 调用机械展开；此模块不读取源码或执行规则。
FORK_PREFIX = "tools/MediaCrawler/"

SYMBOL_ROOT_FILES = (
    "scripts/mediacrawler_crawl.py",
    "scripts/mediacrawler_export_entrypoint.py",
    "scripts/mediacrawler_behavior.py",
    "scripts/human_flow.py",
    "scripts/mediacrawler_login_warmup.py",
    "scripts/login_warmup.py",
    "scripts/failure_classifier.py",
    "scripts/crawl_policy.py",
    "scripts/browser_runtime.py",
    "scripts/execution_state.py",
    "scripts/ctf_browser_resilience.py",
)

FORK_EXCLUDED_DIRS = (".venv", "tests", "test", "webui", "api", "docs", "temp", "data", "browser_data", "__pycache__")

FORK_EXCLUDED_PLATFORMS = ("bilibili", "kuaishou", "tieba", "baidu")

# CLI 契约归属于外部入口；仅工作树漂移检查跟随迁出的定义。
CLI_DEFINITION_SOURCES = {
    "scripts/mediacrawler_crawl.py": ("src/trippostcollect/application/inputs.py",),
    "scripts/login_warmup.py": ("src/trippostcollect/application/warmup.py:parse_args",),
    "scripts/mediacrawler_login_warmup.py": ("src/trippostcollect/application/warmup.py:media_parse_args",),
}

ENTRYPOINTS = (
    "scripts/crawl_runner.py",
    "scripts/login_warmup.py",
    "scripts/mediacrawler_crawl.py",
    "scripts/mediacrawler_login_warmup.py",
    "scripts/repair_post_details.py",
    "scripts/repair_xhs_posts.py",
    "scripts/xhs_runner.py",
)

RESOURCE_FILES = ("libs/douyin.js", "libs/zhihu.js", "libs/stealth.min.js", "LICENSE")

SPEC_MERGE_BASE = "d6f7c5bb906b6dac40ddf343ef9e26438a3de092"

SYMBOL_RULES = [
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:XhsParentNetworkPauseClock(\\..*)?)$",
        "runtime/process.py",
        "迁",
        "T02",
        "F06",
        "XHS父侧网络暂停计时，随run_command",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:Bilibili(ArticleDetailError|FollowerFetchError|RuntimeBlocked)(\\..*)?)$",
        "platforms/bilibili/models.py",
        "迁",
        "T08",
        "F14",
        "retryable/code/attempts/waits元数据不变；B修复脚本反向导入DetailError",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:is_retryable_image_error|is_runtime_blocking_image_error)$",
        "runtime/image_retry.py",
        "并",
        "T04",
        "F05",
        "与M/tools/image_download_retry同名同常量；合并前逐项比对两组错误码集合",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:parse_args)$",
        "application/inputs.py",
        "迁",
        "T02",
        "F10",
        "D2全部参数与默认值不变",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:utc_stamp|_runtime_progress|_runtime_progress_if_due)$",
        "runtime/helpers.py",
        "迁",
        "T02",
        "F06",
        "",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:selected_platforms)$",
        "application/inputs.py",
        "迁",
        "T02",
        "F10",
        "W:90为独立同名实现，不合并",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:load_zhihu_detail_urls|load_xhs_detail_urls|load_xhs_repair_target_ids)$",
        "application/inputs.py",
        "迁",
        "T10",
        "F08",
        "文件输入解析；带token URL不写普通摘要",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:load_post_repair_fallbacks|load_post_repair_targets)$",
        "application/repair.py",
        "迁",
        "T10",
        "F08",
        "",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:ensure_prerequisites)$",
        "core/resources.py",
        "拆",
        "T01",
        "F10",
        "fork文件存在检查改为包资源检查；uv/运行环境检查留入口",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:discover_cdp_browser_path)$",
        "runtime/browser_launcher.py",
        "迁",
        "T01",
        "F07",
        "W反向导入，T10同批切换",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:profile_dir_for|cookie_snapshot_path)$",
        "core/paths.py",
        "并",
        "T01",
        "F10",
        "与W:103/118重复；PLATFORMS代号映射一致后唯一定义",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:required_cookie_names)$",
        "runtime/cookies.py",
        "并",
        "T03",
        "F07",
        "与W:112重复",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:platform_cookie_url|cookie_names_from_header|cookies_to_header|public_cookie_export)$",
        "runtime/cookies.py",
        "迁",
        "T03",
        "F07",
        "",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:load_cookie_snapshot)$",
        "runtime/cookies.py",
        "迁",
        "T03",
        "F07/F08",
        "B修复反向导入",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:export_profile_cookies)$",
        "runtime/cookies.py",
        "迁",
        "T07",
        "F07",
        "见C4；知乎d_c0/z_c0要求不变",
    ),
    ("scripts/mediacrawler_crawl.py", "^(?:load_behavior_evidence)$", "runtime/behavior.py", "迁", "T04", "F07", ""),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:behavior_environment)$",
        "application/collection.py",
        "拆",
        "T02",
        "F07/F10",
        "父侧行为env构造；PROJECT_SCRIPTS在T12移除",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:run_bilibili_behavior_session)$",
        "platforms/bilibili/login.py",
        "拆",
        "T08",
        "F07/F14",
        "见C5；Context关闭后才走urllib",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:decode_text|tail|skipped_command|progress_path_signature|process_group_exists|terminate_managed_process|runtime_watchdog_stop_detail|run_command)$",
        "runtime/process.py",
        "迁",
        "T02",
        "F06",
        "进程组、watchdog、管道净化",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:append_runtime_watchdog_stop_event)$",
        "runtime/process.py",
        "迁",
        "T02",
        "F06",
        "写严格FrozenExecutionState，不走legacy事件",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:_diagnostic_timestamp|_fresh_diagnostic_timestamp|_sanitized_transport_reason|xhs_network_state_from_diagnostics)$",
        "runtime/process.py",
        "迁",
        "T09",
        "F06",
        "XHS网络诊断文件读取与净化",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:XhsRuntimeSupervisionError(\\..*)?)$",
        "application/contracts.py",
        "迁",
        "T02",
        "F05/F06",
        "类型移入contracts，xhs/supervision重导出；db/content仍需按该类型回滚",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:XhsSupervisorRuntimeReporter(\\..*)?|xhs_supervisor_runtime_reporter_from_context)$",
        "xhs/supervision.py",
        "迁",
        "T09",
        "F06",
        "认证心跳，不承担发现提交",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:json_dump|parse_int|first_value|timestamp_to_iso|parse_datetime_text|datetime_value_to_iso|iter_nested_values_for_keys|published_at_for_record|is_video_record|platform_from_path|post_id_for_record|canonical_url_for_record|content_body_for_record|content_text_for_record|formal_record_identity|formal_database_identities|validate_formal_record)$",
        "records/formal.py",
        "迁",
        "T04",
        "F03",
        "纯字段/时间/身份判定",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:merge_repair_fallback_metadata)$",
        "records/formal.py",
        "迁",
        "T04",
        "F08",
        "含0被旧值覆盖分支，见H/R04，不顺手修",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:inject_materialized_images|row_for_record)$",
        "records/formal.py",
        "迁",
        "T04",
        "F03/F05",
        "MaterializedImage仅TYPE_CHECKING导入，见B例外X1",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:item_type_from_path|truncate|extract_sample|summarize_jsonl|summarize_output|summarize_output_with_progress|write_json_with_progress|terminal_summary_envelope|collect_behavior_validation|latest_platform_result_counts|write_markdown)$",
        "application/reporting.py",
        "迁",
        "T11",
        "F04/F10",
        "摘要与样本在首次写出前净化",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:clean_html_text)$",
        "platforms/bilibili/parser.py",
        "迁",
        "T08",
        "F14",
        "仅B站两处调用，不设跨站共享",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:ensure_web_schema|find_existing_post|upsert_web_post|commit_formal_import|import_valid_records|FormalImportBeforeCommitError(\\..*)?)$",
        "db/content.py",
        "迁",
        "T11",
        "F05",
        "事务与提交确定性探测不变",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:stable_douyin_search_id|effective_discovery_checkpoint_event|persist_discovery_checkpoint)$",
        "application/collection.py",
        "迁",
        "T11",
        "F01",
        "抖音search_id提取保持父侧现位置，父进程不导入抖音包",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:load_existing_formal_identities)$",
        "db/discovery_read.py",
        "迁",
        "T08",
        "F01/F14",
        "Bili与收集阶段各读一次",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:load_pagination_evidence|attach_skipped_candidate_evidence|collect_formal_records|effective_attempt_exit_code|apply_formal_completion_gates|formal_import_gate_met|formal_image_promotion_allowed|import_valid_records_with_media_rollback|_run_platform_without_policy|run_platform|_run_main)$",
        "application/collection.py",
        "迁",
        "T11",
        "F01/F03/F05",
        "",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:load_xhs_repair_report|xhs_repair_pagination_evidence|post_repair_pagination_evidence|repair_partial_child_execution_allowed|repair_candidate_execution_completed)$",
        "application/repair.py",
        "迁",
        "T10",
        "F08",
        "",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:repair_runtime_stop_reason)$",
        "application/repair.py",
        "迁",
        "T10",
        "F08",
        "生产代码无调用，仅2个测试引用；T00已定保留，测试不改",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:runtime_blocker_stop_reason|runtime_blocker_from_terminal_event|runtime_blocker_from_pagination_evidence|latest_runtime_blocker|apply_runtime_blocker)$",
        "application/failures.py",
        "迁",
        "T11",
        "F06/F08",
        "运行级阻断裁决",
    ),
    ("scripts/mediacrawler_crawl.py", "^(?:resolve_media_root)$", "artifacts/paths.py", "迁", "T11", "F05", ""),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:_project_relative_evidence_path|_load_manifest_with_evidence|_staging_root_for_manifest_entry|_validated_manifest_rows_for_post|rollback_newly_promoted_images|formal_media_persistence_lock|materialize_formal_record_images)$",
        "artifacts/formal_images.py",
        "迁",
        "T11",
        "F05",
        "正式图片复验、晋升、回滚、媒体锁",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:normalize_bilibili_article_record|clean_bilibili_article_body|normalize_bilibili_detail_image_url|extract_bilibili_detail_images|hydrate_bilibili_article_record)$",
        "platforms/bilibili/parser.py",
        "迁",
        "T08",
        "F14",
        "hydrate不覆盖搜索发布时间",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:bilibili_detail_headers|bilibili_image_headers|fetch_bilibili_image_bytes|fetch_bilibili_article_detail|fetch_bilibili_article_detail_with_retry|fetch_bilibili_article_page|fetch_bilibili_follower_count|fetch_bilibili_wbi_keys)$",
        "platforms/bilibili/client.py",
        "迁",
        "T08",
        "F09/F14",
        "urllib不换；B修复反向导入detail",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:sign_bilibili_wbi_params)$",
        "platforms/bilibili/signer.py",
        "迁",
        "T08",
        "F09",
        "",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:download_bilibili_record_images|run_bilibili_article_search)$",
        "platforms/bilibili/core.py",
        "迁",
        "T08",
        "F01/F05/F14",
        "执行器进程内同步调用",
    ),
    (
        "scripts/mediacrawler_crawl.py",
        "^(?:main)$",
        "scripts/mediacrawler_crawl.py",
        "薄",
        "T11",
        "F10",
        "外部命令名保留，只转发application",
    ),
    (
        "scripts/mediacrawler_export_entrypoint.py",
        "^(?:_find_nested_platform_record)$",
        "runtime/helpers.py",
        "迁",
        "T05",
        "F08",
        "微博/抖音详情共用纯查找",
    ),
    (
        "scripts/mediacrawler_export_entrypoint.py",
        "^(?:_douyin_detail_urls)$",
        "platforms/douyin/client.py",
        "迁",
        "T06",
        "F08",
        "",
    ),
    (
        "scripts/mediacrawler_export_entrypoint.py",
        "^(?:_find_douyin_detail)$",
        "platforms/douyin/parser.py",
        "迁",
        "T06",
        "F08",
        "",
    ),
    (
        "scripts/mediacrawler_export_entrypoint.py",
        "^(?:install_douyin_browser_detail_fallback)$",
        "platforms/douyin/client.py",
        "拆",
        "T06",
        "F08",
        "monkeypatch改为显式repair分支",
    ),
    (
        "scripts/mediacrawler_export_entrypoint.py",
        "^(?:_find_weibo_detail)$",
        "platforms/weibo/parser.py",
        "迁",
        "T05",
        "F08",
        "",
    ),
    (
        "scripts/mediacrawler_export_entrypoint.py",
        "^(?:_weibo_detail_api_url|install_weibo_browser_detail_fallback)$",
        "platforms/weibo/client.py",
        "拆",
        "T05",
        "F08",
        "",
    ),
    (
        "scripts/mediacrawler_export_entrypoint.py",
        "^(?:sanitize_export_item|install_export_hook)$",
        "records/sanitization.py",
        "拆",
        "T04",
        "F04",
        "清理算法复用现有；hook改显式RecordSink",
    ),
    (
        "scripts/mediacrawler_export_entrypoint.py",
        "^(?:install_batch_checkpoint_hook)$",
        "application/events.py",
        "拆",
        "T04",
        "F02",
        "append→publish显式；错误前缀与时点不变",
    ),
    (
        "scripts/mediacrawler_export_entrypoint.py",
        "^(?:_repair_exception_is_blocking|_xhs_repair_failure|_xhs_repair_failure_scope|_xhs_repair_blocker|install_xhs_repair_resilience)$",
        "platforms/xhs/repair.py",
        "拆",
        "T09",
        "F08",
        "",
    ),
    (
        "scripts/mediacrawler_export_entrypoint.py",
        "^(?:_write_xhs_repair_report)$",
        "artifacts/evidence.py",
        "迁",
        "T09",
        "F04/F08",
        "报告仍先净化",
    ),
    (
        "scripts/mediacrawler_export_entrypoint.py",
        "^(?:main)$",
        "platforms/entry.py",
        "拆",
        "T02",
        "F10",
        "runpy桥退出，T14删E",
    ),
    ("scripts/mediacrawler_behavior.py", "^(?:write_evidence)$", "artifacts/evidence.py", "迁", "T04", "F04/F07", ""),
    (
        "scripts/mediacrawler_behavior.py",
        "^(?:record_xhs_platform_security_limit|wait_for_xhs_search_ready|wait_for_xhs_continuity_verification|run_xhs_api_captcha_verification|persist_xhs_continuity_failure|run_xhs_continuity_behavior|_first_visible_locator|_like_control_state|_looks_liked|_looks_unliked|_run_xhs_comment_scroll|_run_xhs_like_once|run_xhs_post_interaction)$",
        "platforms/xhs/behavior.py",
        "迁",
        "T09",
        "F07/F15",
        "XHS特有动作，经窄callback注入runtime",
    ),
    ("scripts/mediacrawler_behavior.py", "^(?:utc_now)$", "runtime/helpers.py", "迁", "T04", "F07", ""),
    (
        "scripts/mediacrawler_behavior.py",
        "^(?:.*)$",
        "runtime/behavior.py",
        "迁",
        "T04",
        "F07",
        "run_page_behavior的xhs_guarded分支改注入callback",
    ),
    ("scripts/human_flow.py", "^(?:.*)$", "runtime/human_flow.py", "迁", "T04", "F07", "profile数值与override语义见D1"),
    (
        "scripts/mediacrawler_login_warmup.py",
        "^(?:profile_dir_for|cookie_snapshot_path)$",
        "core/paths.py",
        "并",
        "T01",
        "F10",
        "与C同名合并",
    ),
    (
        "scripts/mediacrawler_login_warmup.py",
        "^(?:required_cookie_names|cookie_dict|cookie_snapshot_info|write_cookie_snapshot)$",
        "runtime/cookies.py",
        "拆",
        "T10",
        "F07",
        "snapshot chmod/重开验证不变；与C重复项合并",
    ),
    (
        "scripts/mediacrawler_login_warmup.py",
        "^(?:main)$",
        "scripts/mediacrawler_login_warmup.py",
        "薄",
        "T10",
        "F07",
        "",
    ),
    (
        "scripts/mediacrawler_login_warmup.py",
        "^(?:.*)$",
        "application/warmup.py",
        "迁",
        "T10",
        "F07",
        "辅助登录判定不并入worker谓词",
    ),
    ("scripts/login_warmup.py", "^(?:main)$", "scripts/login_warmup.py", "薄", "T10", "F07", ""),
    ("scripts/login_warmup.py", "^(?:.*)$", "application/warmup.py", "迁", "T10", "F07", ""),
    (
        "scripts/failure_classifier.py",
        "^(?:.*)$",
        "application/failures.py",
        "迁",
        "T04",
        "F06/F07/F08",
        "原tests/test_failure_classifier.py随迁",
    ),
    ("scripts/crawl_policy.py", "^(?:.*)$", "application/policy.py", "迁", "T04", "F07", "文件锁/冷却/节流语义不变"),
    ("scripts/browser_runtime.py", "^(?:.*)$", "runtime/browser_runtime.py", "迁", "T02", "F06/F10", ""),
    (
        "scripts/execution_state.py",
        "^(?:.*)$",
        "core/execution_state.py",
        "迁",
        "T04",
        "F02/F06",
        "严格出口，不与legacy事件合并",
    ),
    (
        "scripts/ctf_browser_resilience.py",
        "^(?:is_douyin_target|clean_douyin_profile_cookies|clear_douyin_context_cookies)$",
        "application/page_evidence.py",
        "迁",
        "T10",
        "F10",
        "仅页面证据使用",
    ),
    ("scripts/ctf_browser_resilience.py", "^(?:.*)$", "runtime/page_readiness.py", "迁", "T10", "F10", ""),
    (
        "tools/MediaCrawler/tools/trippostcollect_adaptive.py",
        "^(?:env_int)$",
        "application/worker_inputs.py",
        "拆",
        "T03",
        "F01/F09",
        "四站core读TOP_REFRESH/RESUME值；解析失败回默认值不变",
    ),
    (
        "tools/MediaCrawler/tools/trippostcollect_adaptive.py",
        "^(?:_utc_iso|append_execution_event)$",
        "application/events.py",
        "迁",
        "T04",
        "F02/F09",
        "legacy宽容出口",
    ),
    (
        "tools/MediaCrawler/tools/trippostcollect_adaptive.py",
        "^(?:existing_platform_identities)$",
        "db/discovery_read.py",
        "拆",
        "T03",
        "F01/F09",
        "env读取改显式输入；错误吞并子集不变",
    ),
    (
        "tools/MediaCrawler/tools/trippostcollect_adaptive.py",
        "^(?:AdaptiveAccumulator\\.from_environment)$",
        "application/candidates.py",
        "拆",
        "T03",
        "F01",
        "保留微博stagnation_basis=candidate_identity，其余valid_new",
    ),
    (
        "tools/MediaCrawler/tools/trippostcollect_adaptive.py",
        "^(?:AdaptiveAccumulator(\\..*)?)$",
        "application/candidates.py",
        "迁",
        "T03",
        "F01/F09",
        "",
    ),
    (
        "tools/MediaCrawler/tools/trippostcollect_adaptive.py",
        "^(?:should_reseed_douyin_frontier)$",
        "application/candidates.py",
        "迁",
        "T06",
        "F01/F12",
        "抖音core:611调用；前沿纪元判定属application，经注入端口调用",
    ),
    (
        "tools/MediaCrawler/tools/trippostcollect_behavior.py",
        "^(?:_enabled)$",
        "application/worker_inputs.py",
        "拆",
        "T04",
        "F07",
        "",
    ),
    (
        "tools/MediaCrawler/tools/trippostcollect_behavior.py",
        "^(?:project_browser_args|install_project_runtime_hints|run_required_human_behavior)$",
        "runtime/behavior.py",
        "拆",
        "T04",
        "F07/F10",
        "删除sys.path注入",
    ),
    (
        "tools/MediaCrawler/tools/trippostcollect_behavior.py",
        "^(?:.*)$",
        "platforms/xhs/behavior.py",
        "拆",
        "T09",
        "F07/F15",
        "仅XHS调用的桥入口，改注入callback",
    ),
    ("tools/MediaCrawler/tools/app_runner.py", "^(?:.*)$", "runtime/worker.py", "迁", "T02", "F06", ""),
    (
        "tools/MediaCrawler/tools/async_file_writer.py",
        "^(?:AsyncFileWriter(\\.(__init__|_get_file_path|write_to_jsonl))?)$",
        "artifacts/jsonl.py",
        "迁",
        "T04",
        "F04/F09",
        "实例锁、当日路径、逐条追加不变",
    ),
    ("tools/MediaCrawler/tools/async_file_writer.py", "^(?:.*)$", "—", "退", "T12", "F10", "CSV/单JSON/词云出口"),
    (
        "tools/MediaCrawler/tools/browser_launcher.py",
        "^(?:.*)$",
        "runtime/browser_launcher.py",
        "迁",
        "T02",
        "F06/F07",
        "",
    ),
    ("tools/MediaCrawler/tools/cdp_browser.py", "^(?:.*)$", "runtime/browser.py", "迁", "T02", "F06/F07", ""),
    (
        "tools/MediaCrawler/tools/crawler_util.py",
        "^(?:find_login_qrcode|find_qrcode_img_from_canvas|show_qrcode)$",
        "runtime/login_helpers.py",
        "迁",
        "T02",
        "F07",
        "",
    ),
    (
        "tools/MediaCrawler/tools/crawler_util.py",
        "^(?:convert_cookies|convert_browser_context_cookies|convert_str_cookie_to_dict)$",
        "runtime/cookies.py",
        "迁",
        "T03",
        "F09",
        "",
    ),
    (
        "tools/MediaCrawler/tools/crawler_util.py",
        "^(?:get_user_agent|get_mobile_user_agent|extract_text_from_html|extract_url_params_to_dict)$",
        "runtime/helpers.py",
        "迁",
        "T03",
        "F09",
        "随机UA显式随机源；URL参数解析供DY/XHS",
    ),
    (
        "tools/MediaCrawler/tools/crawler_util.py",
        "^(?:match_interact_info_count)$",
        "—",
        "退",
        "T12",
        "F10",
        "闭包内无调用",
    ),
    (
        "tools/MediaCrawler/tools/crawler_util.py",
        "^(?:format_proxy_info)$",
        "—",
        "退",
        "T12",
        "F10",
        "仅ENABLE_IP_PROXY分支；随proxy切片退出",
    ),
    (
        "tools/MediaCrawler/tools/easing.py",
        "^(?:.*)$",
        "platforms/douyin/login_support.py",
        "迁",
        "T06",
        "F07",
        "仅滑块轨迹",
    ),
    (
        "tools/MediaCrawler/tools/slider_util.py",
        "^(?:.*)$",
        "platforms/douyin/login_support.py",
        "迁",
        "T06",
        "F07",
        "cv2/numpy仅在此处保留",
    ),
    ("tools/MediaCrawler/tools/file_header_manager.py", "^(?:.*)$", "—", "退", "T12", "", "上游开发工具"),
    (
        "tools/MediaCrawler/tools/httpx_util.py",
        "^(?:.*)$",
        "runtime/http.py",
        "迁",
        "T03",
        "F09",
        "verify在每次构造读取",
    ),
    (
        "tools/MediaCrawler/tools/image_download_retry.py",
        "^(?:.*)$",
        "runtime/image_retry.py",
        "迁",
        "T04",
        "F05/F09",
        "四站client使用classified_http_image_error",
    ),
    (
        "tools/MediaCrawler/tools/image_manifest.py",
        "^(?:weibo_source_asset_key)$",
        "platforms/weibo/parser.py",
        "迁",
        "T05",
        "F05/F11",
        "本站图片稳定键",
    ),
    (
        "tools/MediaCrawler/tools/image_manifest.py",
        "^(?:xhs_source_asset_key)$",
        "platforms/xhs/parser.py",
        "迁",
        "T09",
        "F05/F15",
        "",
    ),
    (
        "tools/MediaCrawler/tools/image_manifest.py",
        "^(?:zhihu_source_asset_key)$",
        "platforms/zhihu/parser.py",
        "迁",
        "T07",
        "F05/F13",
        "",
    ),
    (
        "tools/MediaCrawler/tools/image_manifest.py",
        "^(?:douyin_source_asset_key)$",
        "platforms/douyin/parser.py",
        "迁",
        "T06",
        "F05/F12",
        "",
    ),
    (
        "tools/MediaCrawler/tools/image_manifest.py",
        "^(?:normalize_image_url)$",
        "runtime/helpers.py",
        "迁",
        "T04",
        "F05",
        "DY/ZH投影共用纯函数",
    ),
    (
        "tools/MediaCrawler/tools/image_manifest.py",
        "^(?:.*)$",
        "artifacts/image_staging.py",
        "迁",
        "T04",
        "F05",
        "经contracts.ImageStager端口供平台调用",
    ),
    (
        "tools/MediaCrawler/tools/time_util.py",
        "^(?:get_current_timestamp|rfc2822_to_china_datetime|rfc2822_to_timestamp)$",
        "runtime/helpers.py",
        "迁",
        "T05",
        "F03/F11",
        "时钟显式注入",
    ),
    (
        "tools/MediaCrawler/tools/time_util.py",
        "^(?:get_current_date)$",
        "artifacts/jsonl.py",
        "迁",
        "T04",
        "F04",
        "JSONL当日文件名",
    ),
    ("tools/MediaCrawler/tools/time_util.py", "^(?:.*)$", "—", "退", "T12", "", "闭包内无调用"),
    ("tools/MediaCrawler/tools/user_hash.py", "^(?:.*)$", "records/identity.py", "迁", "T04", "F04", ""),
    (
        "tools/MediaCrawler/tools/utils.py",
        "^(?:init_loging_config)$",
        "runtime/worker.py",
        "拆",
        "T04",
        "F04",
        "logger经净化出口",
    ),
    (
        "tools/MediaCrawler/tools/utils.py",
        "^(?:str2bool)$",
        "application/worker_inputs.py",
        "迁",
        "T02",
        "F10",
        "输入集合不变",
    ),
    ("tools/MediaCrawler/tools/words.py", "^(?:.*)$", "—", "退", "T12", "", "词云关闭"),
    (
        "tools/MediaCrawler/main.py",
        "^(?:CrawlerFactory(\\..*)?|_flush_excel_if_needed|_generate_wordcloud_if_needed)$",
        "—",
        "退",
        "T14",
        "F10",
        "全平台注册与关闭的Excel/词云",
    ),
    ("tools/MediaCrawler/main.py", "^(?:main)$", "platforms/entry.py", "拆", "T02", "F10", "选站延迟装配"),
    (
        "tools/MediaCrawler/main.py",
        "^(?:async_cleanup)$",
        "runtime/worker.py",
        "迁",
        "T02",
        "F06",
        "含内嵌_force_stop与信号回收",
    ),
    (
        "tools/MediaCrawler/base/base_crawler.py",
        "^(?:.*)$",
        "—",
        "退",
        "T12",
        "F10",
        "四站解除继承后退出；职责由本站类型与D4端口承接",
    ),
    (
        "tools/MediaCrawler/cmd_arg/arg.py",
        "^(?:_inject_init_db_default|_normalize_tieba_note_id|_normalize_tieba_creator_url)$",
        "—",
        "退",
        "T12",
        "F10",
        "",
    ),
    (
        "tools/MediaCrawler/cmd_arg/arg.py",
        "^(?:.*)$",
        "application/worker_inputs.py",
        "拆",
        "T02",
        "F10",
        "只保留父侧生成参数与原str2bool语义",
    ),
    ("tools/MediaCrawler/cache/abs_cache.py", "^(?:.*)$", "platforms/douyin/login_support.py", "迁", "T06", "F07", ""),
    (
        "tools/MediaCrawler/cache/local_cache.py",
        "^(?:.*)$",
        "platforms/douyin/login_support.py",
        "迁",
        "T06",
        "F07",
        "保留清理task生命周期",
    ),
    (
        "tools/MediaCrawler/cache/cache_factory.py",
        "^(?:.*)$",
        "—",
        "退",
        "T06",
        "F07",
        "改为直接构造MEMORY实现；Redis支路退出",
    ),
    ("tools/MediaCrawler/cache/redis_cache.py", "^(?:.*)$", "—", "退", "T12", "", ""),
    (
        "tools/MediaCrawler/proxy/base_proxy.py",
        "^(?:.*)$",
        "—",
        "退",
        "T12",
        "F09/F10",
        "正式proxy=false；四站client解除ProxyRefreshMixin时保持pool为None的无操作等价",
    ),
    (
        "tools/MediaCrawler/proxy/proxy_ip_pool.py",
        "^(?:.*)$",
        "—",
        "退",
        "T12",
        "F09/F10",
        "正式proxy=false；四站client解除ProxyRefreshMixin时保持pool为None的无操作等价",
    ),
    (
        "tools/MediaCrawler/proxy/proxy_mixin.py",
        "^(?:.*)$",
        "—",
        "退",
        "T12",
        "F09/F10",
        "正式proxy=false；四站client解除ProxyRefreshMixin时保持pool为None的无操作等价",
    ),
    (
        "tools/MediaCrawler/proxy/types.py",
        "^(?:.*)$",
        "—",
        "退",
        "T12",
        "F09/F10",
        "正式proxy=false；四站client解除ProxyRefreshMixin时保持pool为None的无操作等价",
    ),
    (
        "tools/MediaCrawler/proxy/providers/jishu_http_proxy.py",
        "^(?:.*)$",
        "—",
        "退",
        "T12",
        "F09/F10",
        "正式proxy=false；四站client解除ProxyRefreshMixin时保持pool为None的无操作等价",
    ),
    (
        "tools/MediaCrawler/proxy/providers/kuaidl_proxy.py",
        "^(?:.*)$",
        "—",
        "退",
        "T12",
        "F09/F10",
        "正式proxy=false；四站client解除ProxyRefreshMixin时保持pool为None的无操作等价",
    ),
    (
        "tools/MediaCrawler/proxy/providers/wandou_http_proxy.py",
        "^(?:.*)$",
        "—",
        "退",
        "T12",
        "F09/F10",
        "正式proxy=false；四站client解除ProxyRefreshMixin时保持pool为None的无操作等价",
    ),
    ("tools/MediaCrawler/database/db.py", "^(?:.*)$", "—", "退", "T12", "F10", "上游DB/Mongo/Excel存储"),
    ("tools/MediaCrawler/database/db_session.py", "^(?:.*)$", "—", "退", "T12", "F10", "上游DB/Mongo/Excel存储"),
    ("tools/MediaCrawler/database/models.py", "^(?:.*)$", "—", "退", "T12", "F10", "上游DB/Mongo/Excel存储"),
    (
        "tools/MediaCrawler/database/mongodb_store_base.py",
        "^(?:.*)$",
        "—",
        "退",
        "T12",
        "F10",
        "上游DB/Mongo/Excel存储",
    ),
    ("tools/MediaCrawler/store/excel_store_base.py", "^(?:.*)$", "—", "退", "T12", "F10", "上游DB/Mongo/Excel存储"),
    (
        "tools/MediaCrawler/recv_sms.py",
        "^(?:.*)$",
        "—",
        "退",
        "T12",
        "F07",
        "独立短信接收服务；T00已核闭包内无引用",
    ),
    (
        "tools/MediaCrawler/model/m_douyin.py",
        "^(?:VideoUrlInfo)$",
        "platforms/douyin/models.py",
        "迁",
        "T06",
        "F08/F12",
        "图文仍复用",
    ),
    (
        "tools/MediaCrawler/model/m_xiaohongshu.py",
        "^(?:NoteUrlInfo)$",
        "platforms/xhs/models.py",
        "迁",
        "T09",
        "F08",
        "",
    ),
    (
        "tools/MediaCrawler/model/m_zhihu.py",
        "^(?:ZhihuContent|ZhihuCreator)$",
        "platforms/zhihu/models.py",
        "迁",
        "T07",
        "F03/F13",
        "",
    ),
    ("tools/MediaCrawler/model/m_douyin.py", "^(?:.*)$", "—", "退", "T12", "", "creator批采/评论/未选平台模型"),
    ("tools/MediaCrawler/model/m_xiaohongshu.py", "^(?:.*)$", "—", "退", "T12", "", "creator批采/评论/未选平台模型"),
    ("tools/MediaCrawler/model/m_zhihu.py", "^(?:.*)$", "—", "退", "T12", "", "creator批采/评论/未选平台模型"),
    ("tools/MediaCrawler/model/m_bilibili.py", "^(?:.*)$", "—", "退", "T12", "", "creator批采/评论/未选平台模型"),
    ("tools/MediaCrawler/model/m_kuaishou.py", "^(?:.*)$", "—", "退", "T12", "", "creator批采/评论/未选平台模型"),
    ("tools/MediaCrawler/model/m_baidu_tieba.py", "^(?:.*)$", "—", "退", "T12", "", "creator批采/评论/未选平台模型"),
    (
        "tools/MediaCrawler/media_platform/weibo/core.py",
        "^(?:Weibo(ImageDownloadError|FullTextFetchError)(\\..*)?)$",
        "platforms/weibo/models.py",
        "迁",
        "T05",
        "F09/F11",
        "",
    ),
    (
        "tools/MediaCrawler/media_platform/weibo/core.py",
        "^(?:WeiboCrawler\\.(batch_get_notes_comments|get_note_comments|get_creators_and_notes|batch_get_notes_full_text))$",
        "—",
        "退",
        "T12",
        "F11",
        "评论开关关闭/creator批采；batch_get_notes_full_text仅creator链调用",
    ),
    (
        "tools/MediaCrawler/media_platform/weibo/core.py",
        "^(?:WeiboCrawler\\.(launch_browser|launch_browser_with_cdp|close))$",
        "platforms/weibo/core.py",
        "拆",
        "T05",
        "F07",
        "浏览器生命周期交runtime，保留现有CDP失败回退",
    ),
    (
        "tools/MediaCrawler/media_platform/weibo/core.py",
        "^(?:WeiboCrawler\\.create_weibo_client)$",
        "platforms/weibo/core.py",
        "迁",
        "T05",
        "F09",
        "装配client",
    ),
    (
        "tools/MediaCrawler/media_platform/weibo/core.py",
        "^(?:.*)$",
        "platforms/weibo/core.py",
        "迁",
        "T05",
        "F01/F11",
        "",
    ),
    (
        "tools/MediaCrawler/media_platform/weibo/client.py",
        "^(?:WeiboClient\\.(get_note_comments|get_note_all_comments|get_comments_all_sub_comments|get_creator_container_info|get_creator_info_by_id|get_notes_by_creator|get_all_notes_by_creator_id))$",
        "—",
        "退",
        "T12",
        "F11",
        "评论/creator批采",
    ),
    (
        "tools/MediaCrawler/media_platform/weibo/client.py",
        "^(?:.*)$",
        "platforms/weibo/client.py",
        "迁",
        "T05",
        "F09/F11",
        "",
    ),
    (
        "tools/MediaCrawler/media_platform/weibo/exception.py",
        "^(?:IPBlockError)$",
        "—",
        "退",
        "T12",
        "",
        "闭包内无引用（星号导入不计），T00已核",
    ),
    (
        "tools/MediaCrawler/media_platform/weibo/exception.py",
        "^(?:.*)$",
        "platforms/weibo/models.py",
        "迁",
        "T05",
        "F09",
        "",
    ),
    (
        "tools/MediaCrawler/media_platform/weibo/field.py",
        "^(?:.*)$",
        "platforms/weibo/models.py",
        "迁",
        "T05",
        "F09",
        "",
    ),
    (
        "tools/MediaCrawler/media_platform/weibo/help.py",
        "^(?:.*)$",
        "platforms/weibo/parser.py",
        "迁",
        "T05",
        "F11",
        "",
    ),
    (
        "tools/MediaCrawler/media_platform/weibo/login.py",
        "^(?:.*)$",
        "platforms/weibo/login.py",
        "迁",
        "T05",
        "F07",
        "login_by_mobile空实现照迁，不宣称可用",
    ),
    (
        "tools/MediaCrawler/media_platform/douyin/core.py",
        "^(?:DouyinImageDownloadError(\\..*)?)$",
        "platforms/douyin/models.py",
        "迁",
        "T06",
        "F09",
        "",
    ),
    (
        "tools/MediaCrawler/media_platform/douyin/core.py",
        "^(?:DouYinCrawler\\.(batch_get_note_comments|get_comments|get_creators_and_videos|fetch_creator_video_detail|get_aweme_video))$",
        "—",
        "退",
        "T12",
        "F12",
        "评论/creator批采/视频",
    ),
    (
        "tools/MediaCrawler/media_platform/douyin/core.py",
        "^(?:DouYinCrawler\\.(launch_browser|launch_browser_with_cdp|close))$",
        "platforms/douyin/core.py",
        "拆",
        "T06",
        "F07",
        "浏览器生命周期交runtime",
    ),
    (
        "tools/MediaCrawler/media_platform/douyin/core.py",
        "^(?:.*)$",
        "platforms/douyin/core.py",
        "迁",
        "T06",
        "F01/F12",
        "get_aweme_detail由get_specified_awemes:761调用",
    ),
    (
        "tools/MediaCrawler/media_platform/douyin/client.py",
        "^(?:DouYinClient\\.(get_aweme_comments|get_sub_comments|get_aweme_all_comments|get_user_aweme_posts|get_all_user_aweme_posts))$",
        "—",
        "退",
        "T12",
        "F12",
        "评论/creator批采",
    ),
    (
        "tools/MediaCrawler/media_platform/douyin/client.py",
        "^(?:.*)$",
        "platforms/douyin/client.py",
        "迁",
        "T06",
        "F09/F12",
        "",
    ),
    (
        "tools/MediaCrawler/media_platform/douyin/exception.py",
        "^(?:IPBlockError)$",
        "—",
        "退",
        "T12",
        "",
        "闭包内无引用，T00已核",
    ),
    (
        "tools/MediaCrawler/media_platform/douyin/exception.py|tools/MediaCrawler/media_platform/douyin/field.py",
        "^(?:.*)$",
        "platforms/douyin/models.py",
        "迁",
        "T06",
        "F09",
        "",
    ),
    (
        "tools/MediaCrawler/media_platform/douyin/help.py",
        "^(?:get_web_id)$",
        "platforms/douyin/client.py",
        "迁",
        "T06",
        "F09",
        "注入随机源",
    ),
    (
        "tools/MediaCrawler/media_platform/douyin/help.py",
        "^(?:get_a_bogus|get_a_bogus_from_js)$",
        "platforms/douyin/signer.py",
        "迁",
        "T06",
        "F09/F10",
        "模块导入期编译douyin.js时点不变",
    ),
    (
        "tools/MediaCrawler/media_platform/douyin/help.py",
        "^(?:parse_video_info_from_url)$",
        "platforms/douyin/parser.py",
        "迁",
        "T06",
        "F08",
        "",
    ),
    (
        "tools/MediaCrawler/media_platform/douyin/help.py",
        "^(?:get_a_bogus_from_playwright|parse_creator_info_from_url)$",
        "—",
        "退",
        "T12",
        "",
        "",
    ),
    (
        "tools/MediaCrawler/media_platform/douyin/login.py",
        "^(?:DouYinLogin\\.(check_page_display_slider|move_slider))$",
        "platforms/douyin/login_support.py",
        "迁",
        "T06",
        "F07",
        "",
    ),
    (
        "tools/MediaCrawler/media_platform/douyin/login.py",
        "^(?:.*)$",
        "platforms/douyin/login.py",
        "迁",
        "T06",
        "F07",
        "",
    ),
    (
        "tools/MediaCrawler/media_platform/douyin/search_safety.py",
        "^(?:inspect_empty_first_page)$",
        "platforms/douyin/client.py",
        "迁",
        "T06",
        "F12",
        "DOM检查",
    ),
    (
        "tools/MediaCrawler/media_platform/douyin/search_safety.py",
        "^(?:.*)$",
        "platforms/douyin/parser.py",
        "迁",
        "T06",
        "F12",
        "",
    ),
    (
        "tools/MediaCrawler/media_platform/zhihu/core.py",
        "^(?:Zhihu(ImageDownloadError|DetailFetchError)(\\..*)?)$",
        "platforms/zhihu/models.py",
        "迁",
        "T07",
        "F09/F13",
        "",
    ),
    (
        "tools/MediaCrawler/media_platform/zhihu/core.py",
        "^(?:ZhihuCrawler\\.(batch_get_content_comments|get_comments|get_creators_and_notes))$",
        "—",
        "退",
        "T12",
        "F13",
        "",
    ),
    (
        "tools/MediaCrawler/media_platform/zhihu/core.py",
        "^(?:ZhihuCrawler\\._env_float)$",
        "application/worker_inputs.py",
        "拆",
        "T07",
        "F09",
        "settle值改零参reader，读点时刻不变",
    ),
    (
        "tools/MediaCrawler/media_platform/zhihu/core.py",
        "^(?:ZhihuCrawler\\.(launch_browser|launch_browser_with_cdp|close|_activate_latest_zhihu_page|_close_stale_pages))$",
        "platforms/zhihu/core.py",
        "拆",
        "T07",
        "F07",
        "浏览器生命周期交runtime",
    ),
    ("tools/MediaCrawler/media_platform/zhihu/core.py", "^(?:.*)$", "platforms/zhihu/core.py", "迁", "T07", "F13", ""),
    (
        "tools/MediaCrawler/media_platform/zhihu/client.py",
        "^(?:ZhiHuClient\\.(get_root_comments|get_child_comments|get_note_all_comments|get_comments_all_sub_comments|get_creator_info|get_creator_answers|get_creator_articles|get_creator_videos|get_all_anwser_by_creator|get_all_articles_by_creator|get_all_videos_by_creator))$",
        "—",
        "退",
        "T12",
        "F13",
        "评论/creator批采",
    ),
    (
        "tools/MediaCrawler/media_platform/zhihu/client.py",
        "^(?:ZhiHuClient\\.get_video_info)$",
        "platforms/zhihu/client.py",
        "迁",
        "T07",
        "F13",
        "指定详情遇zvideo时调用；照迁，视频由根后置过滤",
    ),
    (
        "tools/MediaCrawler/media_platform/zhihu/client.py",
        "^(?:.*)$",
        "platforms/zhihu/client.py",
        "迁",
        "T07",
        "F09/F13",
        "",
    ),
    (
        "tools/MediaCrawler/media_platform/zhihu/exception.py",
        "^(?:IPBlockError|ForbiddenError)$",
        "—",
        "退",
        "T12",
        "",
        "闭包内无引用，T00已核",
    ),
    (
        "tools/MediaCrawler/media_platform/zhihu/exception.py|tools/MediaCrawler/media_platform/zhihu/field.py",
        "^(?:.*)$",
        "platforms/zhihu/models.py",
        "迁",
        "T07",
        "F09",
        "",
    ),
    (
        "tools/MediaCrawler/media_platform/zhihu/help.py",
        "^(?:sign)$",
        "platforms/zhihu/signer.py",
        "迁",
        "T07",
        "F09/F10",
        "首次签名编译后复用",
    ),
    (
        "tools/MediaCrawler/media_platform/zhihu/help.py",
        "^(?:ZhihuExtractor\\.(extract_comments|_extract_comment|_extract_comment_ip_location|extract_offset|_foramt_gender_text|extract_creator|extract_content_list_from_creator))$",
        "—",
        "退",
        "T12",
        "F13",
        "评论/creator/zvideo详情",
    ),
    (
        "tools/MediaCrawler/media_platform/zhihu/help.py",
        "^(?:.*)$",
        "platforms/zhihu/parser.py",
        "迁",
        "T07",
        "F13",
        "_extract_zvideo_content仍在搜索列表分支中调用，照迁，后由根视频过滤",
    ),
    (
        "tools/MediaCrawler/media_platform/zhihu/login.py",
        "^(?:.*)$",
        "platforms/zhihu/login.py",
        "迁",
        "T07",
        "F07",
        "",
    ),
    (
        "tools/MediaCrawler/media_platform/xhs/core.py",
        "^(?:xhs_cdp_lifecycle_stop_detail|is_recoverable_xhs_navigation_failure|XHS(ImageDownloadError|NoteDetailUnavailable|CreatorProfileUnavailable|NetworkRecoveryTimeout)(\\..*)?)$",
        "platforms/xhs/errors.py",
        "迁",
        "T09",
        "F09/F15",
        "",
    ),
    (
        "tools/MediaCrawler/media_platform/xhs/core.py",
        "^(?:XiaoHongShuCrawler\\.(get_creators_and_notes|fetch_creator_notes_detail|batch_get_note_comments|get_comments|get_notice_video))$",
        "—",
        "退",
        "T12",
        "F15",
        "creator批采/评论/视频",
    ),
    (
        "tools/MediaCrawler/media_platform/xhs/core.py",
        "^(?:XiaoHongShuCrawler\\._env_float)$",
        "application/worker_inputs.py",
        "拆",
        "T09",
        "F09",
        "各操作起点读取改零参reader",
    ),
    (
        "tools/MediaCrawler/media_platform/xhs/core.py",
        "^(?:XiaoHongShuCrawler\\._validate_login_contract)$",
        "application/worker_inputs.py",
        "迁",
        "T09",
        "F07",
        "",
    ),
    (
        "tools/MediaCrawler/media_platform/xhs/core.py",
        "^(?:XiaoHongShuCrawler\\.(_navigation_target_matches|_goto_with_deadline|_utc_now|_install_navigation_observers|_navigation_diagnostics_path|_write_navigation_diagnostics|_page_render_diagnostic|_record_navigation_diagnostic|_wait_for_visible_page_shell|_open_behavior_search_page))$",
        "platforms/xhs/navigation.py",
        "迁",
        "T09",
        "F07/F15",
        "诊断写出经artifacts/evidence",
    ),
    (
        "tools/MediaCrawler/media_platform/xhs/core.py",
        "^(?:XiaoHongShuCrawler\\.(_run_qrcode_login|_single_page_for_login|_profile_ui_visible|_wait_for_initial_page_settle))$",
        "platforms/xhs/login.py",
        "迁",
        "T09",
        "F07/F15",
        "",
    ),
    (
        "tools/MediaCrawler/media_platform/xhs/core.py",
        "^(?:XiaoHongShuCrawler\\.(_request_failure_exception|_request_failure_attempts|_is_login_expired_failure))$",
        "platforms/xhs/errors.py",
        "迁",
        "T09",
        "F09/F15",
        "",
    ),
    (
        "tools/MediaCrawler/media_platform/xhs/core.py",
        "^(?:XiaoHongShuCrawler\\.(_maybe_run_post_interaction))$",
        "platforms/xhs/behavior.py",
        "迁",
        "T09",
        "F07",
        "一次互动latch",
    ),
    (
        "tools/MediaCrawler/media_platform/xhs/core.py",
        "^(?:XiaoHongShuCrawler\\.(enrich_note_creator|_raise_for_creator_page_terminal|_get_creator_info_from_browser|_recover_creator_login_on_primary_page|_wait_for_creator_profile_verification))$",
        "platforms/xhs/author.py",
        "迁",
        "T09",
        "F15",
        "",
    ),
    (
        "tools/MediaCrawler/media_platform/xhs/core.py",
        "^(?:XiaoHongShuCrawler\\.(get_specified_notes|get_note_detail_async_task))$",
        "platforms/xhs/detail.py",
        "迁",
        "T09",
        "F08/F15",
        "",
    ),
    (
        "tools/MediaCrawler/media_platform/xhs/core.py",
        "^(?:XiaoHongShuCrawler\\.(is_video_note|note_detail_summaries))$",
        "platforms/xhs/parser.py",
        "迁",
        "T09",
        "F15",
        "",
    ),
    (
        "tools/MediaCrawler/media_platform/xhs/core.py",
        "^(?:XiaoHongShuCrawler\\.(get_notice_media|get_note_images))$",
        "platforms/xhs/media.py",
        "迁",
        "T09",
        "F05/F15",
        "视频分支保持禁用",
    ),
    (
        "tools/MediaCrawler/media_platform/xhs/core.py",
        "^(?:XiaoHongShuCrawler(\\.(__init__|start|search|create_xhs_client))?)$",
        "platforms/xhs/core.py",
        "迁",
        "T09",
        "F01/F15",
        "search/session编排",
    ),
    (
        "tools/MediaCrawler/media_platform/xhs/core.py",
        "^(?:XiaoHongShuCrawler\\..*)$",
        "platforms/xhs/session.py",
        "迁",
        "T09",
        "F07/F15",
        "页守卫、弹窗、网络恢复、主Page存活、浏览器生命周期",
    ),
    (
        "tools/MediaCrawler/media_platform/xhs/client.py",
        "^(?:XiaoHongShuClient\\.(get_note_comments|get_note_sub_comments|get_note_all_comments|get_comments_all_sub_comments|get_notes_by_creator|get_all_notes_by_creator|get_note_short_url))$",
        "—",
        "退",
        "T12",
        "F15",
        "评论/creator批采/无调用短链",
    ),
    (
        "tools/MediaCrawler/media_platform/xhs/client.py",
        "^(?:XiaoHongShuClient\\.extract_creator_info_from_html)$",
        "platforms/xhs/client.py",
        "迁",
        "T09",
        "F15",
        "委托parser",
    ),
    (
        "tools/MediaCrawler/media_platform/xhs/client.py",
        "^(?:.*)$",
        "platforms/xhs/client.py",
        "迁",
        "T09",
        "F09/F15",
        "_build_query_string保证签名与发送编码一致",
    ),
    (
        "tools/MediaCrawler/media_platform/xhs/exception.py",
        "^(?:.*)$",
        "platforms/xhs/errors.py",
        "迁",
        "T09",
        "F09",
        "",
    ),
    (
        "tools/MediaCrawler/media_platform/xhs/extractor.py",
        "^(?:.*)$",
        "platforms/xhs/parser.py",
        "迁",
        "T09",
        "F15",
        "",
    ),
    (
        "tools/MediaCrawler/media_platform/xhs/field.py",
        "^(?:FeedType|NoteType|Note)$",
        "—",
        "退",
        "T12",
        "",
        "闭包内无引用",
    ),
    ("tools/MediaCrawler/media_platform/xhs/field.py", "^(?:.*)$", "platforms/xhs/models.py", "迁", "T09", "F09", ""),
    (
        "tools/MediaCrawler/media_platform/xhs/help.py",
        "^(?:base36encode|get_search_id|parse_note_info_from_note_url)$",
        "platforms/xhs/parser.py",
        "迁",
        "T09",
        "F15",
        "search_id的时钟/随机由core注入",
    ),
    (
        "tools/MediaCrawler/media_platform/xhs/help.py",
        "^(?:.*)$",
        "—",
        "退",
        "T12",
        "F09",
        "旧签名算法/仅__main__或creator链调用",
    ),
    (
        "tools/MediaCrawler/media_platform/xhs/xhs_sign.py",
        "^(?:get_trace_id)$",
        "platforms/xhs/signer.py",
        "迁",
        "T09",
        "F09",
        "x-b3-traceid随机回退",
    ),
    ("tools/MediaCrawler/media_platform/xhs/xhs_sign.py", "^(?:.*)$", "—", "退", "T12", "F09", "旧算法，无调用"),
    (
        "tools/MediaCrawler/media_platform/xhs/playwright_sign.py",
        "^(?:.*)$",
        "platforms/xhs/signer.py",
        "迁",
        "T09",
        "F09",
        "延迟import xhshow，每次新建实例",
    ),
    (
        "tools/MediaCrawler/media_platform/xhs/login.py",
        "^(?:.*)$",
        "platforms/xhs/login.py",
        "迁",
        "T09",
        "F07/F15",
        "",
    ),
    (
        "tools/MediaCrawler/media_platform/xhs/manual_wait.py",
        "^(?:.*)$",
        "platforms/xhs/manual_wait.py",
        "迁",
        "T09",
        "F07/F15",
        "全轮单实例",
    ),
    (
        "tools/MediaCrawler/store/weibo/__init__.py",
        "^(?:WeibostoreFactory(\\..*)?|batch_update_weibo_notes|batch_update_weibo_note_comments|update_weibo_note_comment|save_creator)$",
        "—",
        "退",
        "T12",
        "F11",
        "评论/creator/工厂/视频",
    ),
    (
        "tools/MediaCrawler/store/weibo/__init__.py",
        "^(?:update_weibo_note_images|record_weibo_note_image_failure)$",
        "platforms/weibo/core.py",
        "拆",
        "T05",
        "F05",
        "图片写出改经ImageStager端口",
    ),
    (
        "tools/MediaCrawler/store/weibo/__init__.py",
        "^(?:.*)$",
        "platforms/weibo/parser.py",
        "迁",
        "T05",
        "F03/F04",
        "纯投影；写出经RecordSink",
    ),
    (
        "tools/MediaCrawler/store/weibo/_store_impl.py",
        "^(?:.*JsonlStoreImplement(\\.(__init__|store_content|flush))?)$",
        "artifacts/jsonl.py",
        "拆",
        "T05",
        "F04/F09",
        "仅JSONL内容出口",
    ),
    (
        "tools/MediaCrawler/store/weibo/_store_impl.py",
        "^(?:.*)$",
        "—",
        "退",
        "T12",
        "F10",
        "CSV/DB/JSON/SQLite/Mongo/Excel及评论/creator出口",
    ),
    ("tools/MediaCrawler/store/weibo/weibo_store_media.py", "^(?:.*Video(\\..*)?)$", "—", "退", "T12", "", "视频"),
    (
        "tools/MediaCrawler/store/weibo/weibo_store_media.py",
        "^(?:.*)$",
        "artifacts/image_staging.py",
        "拆",
        "T05",
        "F05",
        "四站实现逐行差分；一致部分合并，差异作显式参数",
    ),
    (
        "tools/MediaCrawler/store/douyin/__init__.py",
        "^(?:DouyinStoreFactory(\\..*)?|_extract_comment_image_list|batch_update_dy_aweme_comments|update_dy_aweme_comment|save_creator|update_dy_aweme_video)$",
        "—",
        "退",
        "T12",
        "F12",
        "评论/creator/工厂/视频",
    ),
    (
        "tools/MediaCrawler/store/douyin/__init__.py",
        "^(?:update_dy_aweme_images|record_dy_aweme_image_failure)$",
        "platforms/douyin/core.py",
        "拆",
        "T06",
        "F05",
        "图片写出改经ImageStager端口",
    ),
    (
        "tools/MediaCrawler/store/douyin/__init__.py",
        "^(?:.*)$",
        "platforms/douyin/parser.py",
        "迁",
        "T06",
        "F03/F04",
        "纯投影；写出经RecordSink",
    ),
    (
        "tools/MediaCrawler/store/douyin/_store_impl.py",
        "^(?:.*JsonlStoreImplement(\\.(__init__|store_content|flush))?)$",
        "artifacts/jsonl.py",
        "拆",
        "T06",
        "F04/F09",
        "仅JSONL内容出口",
    ),
    (
        "tools/MediaCrawler/store/douyin/_store_impl.py",
        "^(?:.*)$",
        "—",
        "退",
        "T12",
        "F10",
        "CSV/DB/JSON/SQLite/Mongo/Excel及评论/creator出口",
    ),
    ("tools/MediaCrawler/store/douyin/douyin_store_media.py", "^(?:.*Video(\\..*)?)$", "—", "退", "T12", "", "视频"),
    (
        "tools/MediaCrawler/store/douyin/douyin_store_media.py",
        "^(?:.*)$",
        "artifacts/image_staging.py",
        "拆",
        "T06",
        "F05",
        "四站实现逐行差分；一致部分合并，差异作显式参数",
    ),
    (
        "tools/MediaCrawler/store/zhihu/__init__.py",
        "^(?:ZhihuStoreFactory(\\..*)?|batch_update_zhihu_contents|batch_update_zhihu_note_comments|update_zhihu_content_comment|save_creator)$",
        "—",
        "退",
        "T12",
        "F13",
        "评论/creator/工厂/视频",
    ),
    (
        "tools/MediaCrawler/store/zhihu/__init__.py",
        "^(?:update_zhihu_content_images|record_zhihu_content_image_failure)$",
        "platforms/zhihu/core.py",
        "拆",
        "T07",
        "F05",
        "图片写出改经ImageStager端口",
    ),
    (
        "tools/MediaCrawler/store/zhihu/__init__.py",
        "^(?:.*)$",
        "platforms/zhihu/parser.py",
        "迁",
        "T07",
        "F03/F04",
        "纯投影；写出经RecordSink",
    ),
    (
        "tools/MediaCrawler/store/zhihu/_store_impl.py",
        "^(?:.*JsonlStoreImplement(\\.(__init__|store_content|flush))?)$",
        "artifacts/jsonl.py",
        "拆",
        "T07",
        "F04/F09",
        "仅JSONL内容出口",
    ),
    (
        "tools/MediaCrawler/store/zhihu/_store_impl.py",
        "^(?:.*)$",
        "—",
        "退",
        "T12",
        "F10",
        "CSV/DB/JSON/SQLite/Mongo/Excel及评论/creator出口",
    ),
    ("tools/MediaCrawler/store/zhihu/zhihu_store_media.py", "^(?:.*Video(\\..*)?)$", "—", "退", "T12", "", "视频"),
    (
        "tools/MediaCrawler/store/zhihu/zhihu_store_media.py",
        "^(?:.*)$",
        "artifacts/image_staging.py",
        "拆",
        "T07",
        "F05",
        "四站实现逐行差分；一致部分合并，差异作显式参数",
    ),
    (
        "tools/MediaCrawler/store/xhs/__init__.py",
        "^(?:XhsStoreFactory(\\..*)?|get_video_url_arr|batch_update_xhs_note_comments|update_xhs_note_comment|save_creator|update_xhs_note_video)$",
        "—",
        "退",
        "T12",
        "F15",
        "评论/creator/工厂/视频",
    ),
    (
        "tools/MediaCrawler/store/xhs/__init__.py",
        "^(?:update_xhs_note_images|record_xhs_note_image_failure)$",
        "platforms/xhs/core.py",
        "拆",
        "T09",
        "F05",
        "图片写出改经ImageStager端口",
    ),
    (
        "tools/MediaCrawler/store/xhs/__init__.py",
        "^(?:.*)$",
        "platforms/xhs/parser.py",
        "迁",
        "T09",
        "F03/F04",
        "纯投影；写出经RecordSink",
    ),
    (
        "tools/MediaCrawler/store/xhs/_store_impl.py",
        "^(?:.*JsonlStoreImplement(\\.(__init__|store_content|flush))?)$",
        "artifacts/jsonl.py",
        "拆",
        "T09",
        "F04/F09",
        "仅JSONL内容出口",
    ),
    (
        "tools/MediaCrawler/store/xhs/_store_impl.py",
        "^(?:.*)$",
        "—",
        "退",
        "T12",
        "F10",
        "CSV/DB/JSON/SQLite/Mongo/Excel及评论/creator出口",
    ),
    ("tools/MediaCrawler/store/xhs/xhs_store_media.py", "^(?:.*Video(\\..*)?)$", "—", "退", "T12", "", "视频"),
    (
        "tools/MediaCrawler/store/xhs/xhs_store_media.py",
        "^(?:.*)$",
        "artifacts/image_staging.py",
        "拆",
        "T09",
        "F05",
        "四站实现逐行差分；一致部分合并，差异作显式参数",
    ),
]
